add solarized dark json theme
lgienapp/aquarel pull request #37
Opened 2024-10-11 14:20 UTC by gennaro-tedesco

This PR adds a custom json theme representing the solarized dark colour palette.

It mirrors a [PR](https://github.com/matplotlib/matplotlib/pull/17325) that I opened some time ago for matplotlib (ignored ever since). The style of the graphs and plots is exactly what you see in the images on the comments on the original PR.

If you find it relevant I could also add screenshots to the README showcases the palette onto the [plot images](https://github.com/lgienapp/aquarel?tab=readme-ov-file#themes) that you use.

2024-10-29 09:58 UTC, lgienapp requested changes

2024-10-29 09:58 UTC, lgienapp commented on aquarel/themes/solarized_dark.json
> +    "name": "arctic_dark",
Adapt to solarized dark

2024-10-29 09:58 UTC, lgienapp commented on aquarel/themes/solarized_dark.json
> +    "description": "Frosty dark theme based on the nord color scheme"
Add description

2024-10-29 09:58 UTC, lgienapp commented on aquarel/themes/solarized_dark.json
Some additional things I think are needed before merging:

- add a corresponding `solarized_light.json` to make the theme feature-complete
- add sample plots as produced by https://github.com/lgienapp/aquarel/blob/114ba2796d2061dd0ac841c0e982ad0ae2ec0c99/aquarel/utils.py#L123 for this theme
- add the theme to the README list of themes

2024-10-29 11:08 UTC, gennaro-tedesco commented
Thank you for reviewing the PR, I will address the comments between today and tomorrow :)

2024-10-29 14:37 UTC, gennaro-tedesco commented on aquarel/themes/solarized_dark.json
I have added a light theme in commit 09fb4ff25ef786c03366e19add53cf9ae05f7edb

I am however having difficulties in running `make_samples()`. If I try to run it from `aquarel` as a module then I get the following exception
```python
Traceback (most recent call last):
  File "~/plot/hello.py", line 3, in <module>
    make_samples()
    ~~~~~~~~~~~~^^
  File "~/plot/.venv/lib/python3.13/site-packages/aquarel/utils.py", line 101, in make_samples
    _sample_plot(theme, f"assets/{theme}.png")
    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "~/plot/.venv/lib/python3.13/site-packages/aquarel/utils.py", line 57, in _sample_plot
    with theme:
         ^^^^^
  File "~/plot/.venv/lib/python3.13/site-packages/aquarel/theme.py", line 233, in __enter__
    self.apply()
    ~~~~~~~~~~^^
  File "~/plot/.venv/lib/python3.13/site-packages/aquarel/theme.py", line 307, in apply
    mapped_key = self._rcparams_mapping[top_key][key]
```
most likely because [this path](https://github.com/lgienapp/aquarel/blob/114ba2796d2061dd0ac841c0e982ad0ae2ec0c99/aquarel/utils.py#L44) isn't found with respect to a local installation in a venv. If I instead run it from within the `aquarel` project (creating a new script and invoking the function) then I get
```python
  File "~/aquarel/aquarel/theme.py", line 2, in <module>
    from cycler import cycler
ModuleNotFoundError: No module named 'cycler'
```
What is the preferred way to run it?

2024-10-31 10:41 UTC, gennaro-tedesco commented on aquarel/themes/solarized_dark.json
I have installed all needed dependencies and have run `make_samples()` from within the project path. I still get the same error
```python
Traceback (most recent call last):
  File "~/plot/hello.py", line 3, in <module>
    make_samples()
    ~~~~~~~~~~~~^^
  File "~/plot/.venv/lib/python3.13/site-packages/aquarel/utils.py", line 101, in make_samples
    _sample_plot(theme, f"assets/{theme}.png")
    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "~/plot/.venv/lib/python3.13/site-packages/aquarel/utils.py", line 57, in _sample_plot
    with theme:
         ^^^^^
  File "~/plot/.venv/lib/python3.13/site-packages/aquarel/theme.py", line 233, in __enter__
    self.apply()
    ~~~~~~~~~~^^
  File "~/plot/.venv/lib/python3.13/site-packages/aquarel/theme.py", line 307, in apply
    mapped_key = self._rcparams_mapping[top_key][key]
```
could you point me in the right direction (also can you reproduce the error at all)?

2024-12-10 14:48 UTC, lgienapp commented on aquarel/themes/solarized_dark.json
> What is the preferred way to run it?

From within the project. 

> `ModuleNotFoundError: No module named 'cycler'` 
The root cause of this is that `cycler` package is not installed in your environment. This is a dev dependency of aquarel (see [here](https://github.com/lgienapp/aquarel/blob/114ba2796d2061dd0ac841c0e982ad0ae2ec0c99/setup.py#L23)). Installing it correctly should solve the previous problems and produce the sample plots.

2024-12-11 12:07 UTC, gennaro-tedesco commented on aquarel/themes/solarized_dark.json
Let me show you what I have done, perhaps I am doing something trivially wrong.

In the project directory I have installed the project as package
```bash
$ pwd
~/aquarel

$ uv pip install .
 
$ uv pip freeze
aquarel @ file:///Users/g.tedesco/aquarel
contourpy==1.3.1
cycler==0.12.1
fonttools==4.55.3
kiwisolver==1.4.7
matplotlib==3.9.3
numpy==2.2.0
packaging==24.2
pandas==2.2.3
pillow==11.0.0
pyparsing==3.2.0
python-dateutil==2.9.0.post0
pytz==2024.2
seaborn==0.13.2
six==1.17.0
tzdata==2024.2
```
the module `cycler` is indeed installed. I then created `sample.py`
```python
from aquarel.utils import make_samples

make_samples()
```
which, upon running, gives
```bash
uv run samples.py
Traceback (most recent call last):
  File "/Users/g.tedesco/aquarel/samples.py", line 3, in <module>
    make_samples()
    ~~~~~~~~~~~~^^
  File "/Users/g.tedesco/aquarel/aquarel/utils.py", line 128, in make_samples
    _sample_plot(theme, f"assets/{theme}.png")
    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/g.tedesco/aquarel/aquarel/utils.py", line 99, in _sample_plot
    with theme:
         ^^^^^
  File "/Users/g.tedesco/aquarel/aquarel/theme.py", line 233, in __enter__
    self.apply()
    ~~~~~~~~~~^^
  File "/Users/g.tedesco/aquarel/aquarel/theme.py", line 307, in apply
    mapped_key = self._rcparams_mapping[top_key][key]
                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
KeyError: 'stretch'
```

2024-12-11 17:44 UTC, lgienapp commented on aquarel/themes/solarized_dark.json
Okay, this a new error now, but your `make_samples()` call is working correctly at least. This error originates from a bug in the `gruxbox-*` themes, were a font option not supported by aquarel (`font.stretch`; its unsupported because it is currently not used in matplotlib) was erroneously included. 

I pushed [a hotfix](https://github.com/lgienapp/aquarel/commit/5d755176c8447497fe44f43c24c3a9d84c64ec8e) on the main branch, if you pull these changes, your code should execute without error now. 

Thanks for continuing work on this PR!

2024-12-11 20:45 UTC, gennaro-tedesco commented on aquarel/themes/solarized_dark.json
Thank you for the hotfix, I have generated the samples successfully and added the corresponding reference in the README in [9827c519a5eec2133f8611a014e0dd735c708be7](https://github.com/gennaro-tedesco/aquarel/commit/9827c519a5eec2133f8611a014e0dd735c708be7). 

Notice the references point to _your_ url `https://github.com/lgienapp/aquarel/blob/main/assets/<name>.png?raw=true`, which obviously doesn't contain the images yet before merging (that's why you'd see an empty column in the README). After merging the references should correctly show in the README.

2024-12-28 12:54 UTC, gennaro-tedesco commented
Is anything else needed for this PR?

2025-01-23 21:21 UTC, lgienapp approved these changes

2025-01-23 21:21 UTC, merged